name: flutter_next_auth_bloc
version: 0.0.1
publish_to: none
environment:
  sdk: ">=3.10.4 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  flutter_next_auth:
    path: ../flutter_next_auth

  flutter_bloc: ^9.1.0
